Update patch set 1
Patch Set 1:

> > Not sure why the cbs test is suddenly showing a missing
 > dependency,
 > > but I want to register my approval of this change from the cinder
 > > point of view.
 > 
 > Error: Package: python2-taskflow-3.5.0-1.el7.noarch (build)
 > Requires: python-networkx-core
 > 
 > python-networkx-core is provided by python-networkx(which is there
 > in stein-testing and -release):- rpm -qp --provides
 > https://cbs.centos.org/kojifiles/packages/python-networkx/2.2/3.el7/noarch/python2-networkx-2.2-3.el7.noarch.rpm
 > python-networkx = 2.2-3.el7
 > python-networkx-core = 2.2-3.el7
 > python-networkx-drawing = 2.2-3.el7
 > python-networkx-geo = 2.2-3.el7
 > python2-networkx = 2.2-3.el7
 > python2-networkx-core = 2.2-3.el7
 > python2-networkx-drawing = 2.2-3.el7
 > python2-networkx-geo = 2.2-3.el7
 > 
 > possibly seems some issue with cbs buildroot, will check it today.

Ok i checked and got what's the issue, yesterday tag inheritance was fixed for stein/rocky with https://bugs.centos.org/view.php?id=16534#c35554, and with this -candidate have high priority than -testing(which is correct), but with this a wrong build of networkx which don't provide[1] python-networkx-core was included in CBS. I have untagged the wrong build using: cbs untag-build cloud7-openstack-stein-candidate python-networkx-2.2-2.el7, this should be clear in few minutes once cbs repo get's updated.

[1] rpm -qp --provides https://cbs.centos.org/kojifiles/packages/python-networkx/2.2/2.el7/noarch/python2-networkx-2.2-2.el7.noarch.rpm
python-networkx = 2.2-2.el7
python2-networkx = 2.2-2.el7
python2-networkx-core = 2.2-2.el7
python2-networkx-drawing = 2.2-2.el7
python2-networkx-geo = 2.2-2.el7

Patch-set: 1