Update patch set 1
Patch Set 1:

> Not sure why the cbs test is suddenly showing a missing dependency,
 > but I want to register my approval of this change from the cinder
 > point of view.

Error: Package: python2-taskflow-3.5.0-1.el7.noarch (build)
           Requires: python-networkx-core

python-networkx-core is provided by python-networkx(which is there in stein-testing and -release):- rpm -qp --provides https://cbs.centos.org/kojifiles/packages/python-networkx/2.2/3.el7/noarch/python2-networkx-2.2-3.el7.noarch.rpm
python-networkx = 2.2-3.el7
python-networkx-core = 2.2-3.el7
python-networkx-drawing = 2.2-3.el7
python-networkx-geo = 2.2-3.el7
python2-networkx = 2.2-3.el7
python2-networkx-core = 2.2-3.el7
python2-networkx-drawing = 2.2-3.el7
python2-networkx-geo = 2.2-3.el7

possibly seems some issue with cbs buildroot, will check it today.

Patch-set: 1