Update patch set 1
Patch Set 1:

TypeError: 'OptGroup' object is not iterable

must be some master change in oslo.config

Patch-set: 1
Reviewer: Gerrit User 85 <85@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Workflow=0